package main

import (
	"go/token"
	"os"
	"path/filepath"
	"testing"
)

func TestAllowed(t *testing.T) {
	tests := []struct {
		text string
		want bool
	}{
		{"//go:build race", true},
		{"//go:generate go run ./gen", true},
		{"//go:embed assets", true},
		{"//nolint:errcheck", true},
		{"//line foo.go:10", true},
		{"//export Add", true},
		{"// +build linux", true},
		{"// Code generated by go run ./gen; DO NOT EDIT.", true},
		{"// Package fixture builds data.", false},
		{"// go:build race", false},
		{"// Code generated by hand.", false},
		{"/* block */", false},
		{"//", false},
	}
	for _, tt := range tests {
		if got := allowed(tt.text); got != tt.want {
			t.Errorf("allowed(%q) = %v; want %v", tt.text, got, tt.want)
		}
	}
}

func TestCheck(t *testing.T) {
	root := t.TempDir()
	write := func(rel, src string) {
		path := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("a.go", "//go:build linux\n\npackage a\n\n// Doc says hi.\nfunc F() string { return \"// not a comment\" }\n")
	write("b.go", "package a\n\nvar x = 1 /* trailing */\n")
	write(".hidden/c.go", "package c\n\n// ignored\n")
	write("testdata/d.go", "package d\n\n// ignored\n")
	write("notes.txt", "// not go\n")

	var got []string
	err := check(root, func(pos token.Position, text string) {
		rel, _ := filepath.Rel(root, pos.Filename)
		got = append(got, filepath.ToSlash(rel)+" "+text)
	})
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"a.go // Doc says hi.", "b.go /* trailing */"}
	if len(got) != len(want) {
		t.Fatalf("got %q; want %q", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("got[%d] = %q; want %q", i, got[i], want[i])
		}
	}
}
